- name: add-apt-repository ppa:nginx/stable
  apt_repository: repo='ppa:nginx/stable'
- name: apt-get update
  apt: update_cache=yes
- name: install nginx
  apt: name=nginx state=latest
- name: Copy nginx configuration for wordpress
  template: src=default.conf dest=/etc/nginx/conf.d/default
  notify: restart nginx

